#!/bin/bash

# Scale the django app deployment to 3 replicas
echo "Scaling deployment to 3 replicas..."
kubectl scale deployment messaging_app --replicas=3

# Waiting a little so kubernetes has time to spin up new pods
sleep 5

# show running pods
echo "checking running pods..."
kubectl get pods

# Finding the service URL
echo "Getting minikube service Url..."
APP_URL=$(minikube service messaging_app --url)

# Using wrk to do a load test
echo "Running load test using wrk..."
wrk -t2 -c10 -d10s "$APP_URL"

# Check resource usage
echo "Monitoring resource usage..."
kubectl top pods