#!/usr/bin/env bash

echo "Deploying Blue version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying green version..."
kubectl apply -f green_deployment.yaml

echo "Checking logs for green pod..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs "$GREEN_POD"

echo "If logs look good, update kubeservice.yaml to point to version=green"